function [...
    tau_cntrl_FR1, tau_cntrl_FR2, xdesFR, ydesFR, thFR1des, thFR2des, ...
    tau_cntrl_HR1, tau_cntrl_HR2, xdesHR, ydesHR, thHR1des, thHR2des, ...
    tau_cntrl_FL1, tau_cntrl_FL2, xdesFL, ydesFL, thFL1des, thFL2des, ...
    tau_cntrl_HL1, tau_cntrl_HL2, xdesHL, ydesHL, thHL1des, thHL2des] = ...
    main_controller(...
    phiFR1, phiFR1dot, phiFR2, phiFR2dot, ...
    phiHR1, phiHR1dot, phiHR2, phiHR2dot,...
    phiFL1, phiFL1dot, phiFL2, phiFL2dot,...
    phiHL1, phiHL1dot, phiHL2, phiHL2dot, t)


    % Trajectory parameters Fore Legs
    x_ell_cntr_F = -0.05;
    y_ell_cntr_F = -0.55;
    a_ell_F = 0.08;
    b_ell_F = 0.11;
    traj_vel_F = 0.7;
    kp_F = 5000;
    kd_F = 2000;
    
    % Trajectory parameters Hind Legs
    x_ell_cntr_H = -0.10;
    y_ell_cntr_H = -0.55;
    a_ell_H = 0.08;
    b_ell_H = 0.11;
    traj_vel_H = 0.7;
    kp_H = 5000;
    kd_H = 2000;
   
    % Phase for each leg
    phaseFR = 0;
    phaseHR = pi;
    phaseFL = pi;
    phaseHL = 0;

    % FR leg controller
    [tau_cntrl_FR1, tau_cntrl_FR2, xdesFR, ydesFR, thFR1des, thFR2des] ...
        = traj_controller_2(phiFR1, phiFR1dot, phiFR2, phiFR2dot, t,...
        x_ell_cntr_F, y_ell_cntr_F, a_ell_F, b_ell_F, traj_vel_F, ...
        kp_F, kd_F, phaseFR);

    % HR leg controller
    [tau_cntrl_HR1, tau_cntrl_HR2, xdesHR, ydesHR, thHR1des, thHR2des] ...
        = traj_controller_2(phiHR1, phiHR1dot, phiHR2, phiHR2dot, t,...
        x_ell_cntr_H, y_ell_cntr_H, a_ell_H, b_ell_H, traj_vel_H, ...
        kp_H, kd_H, phaseHR);

    % FL leg controller
    [tau_cntrl_FL1, tau_cntrl_FL2, xdesFL, ydesFL, thFL1des, thFL2des] ...
        = traj_controller_2(phiFL1, phiFL1dot, phiFL2, phiFL2dot, t,...
        x_ell_cntr_F, y_ell_cntr_F, a_ell_F, b_ell_F, traj_vel_F, ...
        kp_F, kd_F, phaseFL);

    % HL leg controller
    [tau_cntrl_HL1, tau_cntrl_HL2, xdesHL, ydesHL, thHL1des, thHL2des] ...
        = traj_controller_2(phiHL1, phiHL1dot, phiHL2, phiHL2dot, t,...
        x_ell_cntr_H, y_ell_cntr_H, a_ell_H, b_ell_H, traj_vel_H, ...
        kp_H, kd_H, phaseHL);
    
end

