function [...
    tau_cntrl_FR1, tau_cntrl_FR2, xdesFR, ydesFR, thFR1des, thFR2des, ...
    tau_cntrl_HR1, tau_cntrl_HR2, xdesHR, ydesHR, thHR1des, thHR2des, ...
    tau_cntrl_FL1, tau_cntrl_FL2, xdesFL, ydesFL, thFL1des, thFL2des, ...
    tau_cntrl_HL1, tau_cntrl_HL2, xdesHL, ydesHL, thHL1des, thHL2des] = ...
    main_controller_2(...
    phiFR1, phiFR1dot, phiFR2, phiFR2dot, ...
    phiHR1, phiHR1dot, phiHR2, phiHR2dot,...
    phiFL1, phiFL1dot, phiFL2, phiFL2dot,...
    phiHL1, phiHL1dot, phiHL2, phiHL2dot, t)

    % FR leg controller
    [tau_cntrl_FR1, tau_cntrl_FR2, xdesFR, ydesFR, thFR1des, thFR2des] =...
        controller(phiFR1, phiFR1dot, phiFR2, phiFR2dot, t);

    % HR leg controller
    [tau_cntrl_HR1, tau_cntrl_HR2, xdesHR, ydesHR, thHR1des, thHR2des] =...
        controller(phiHR1, phiHR1dot, phiHR2, phiHR2dot, t);

    % FL leg controller
    [tau_cntrl_FL1, tau_cntrl_FL2, xdesFL, ydesFL, thFL1des, thFL2des] =...
        controller(phiFL1, phiFL1dot, phiFL2, phiFL2dot, t);

    % HL leg controller
    [tau_cntrl_HL1, tau_cntrl_HL2, xdesHL, ydesHL, thHL1des, thHL2des] =...
        controller(phiHL1, phiHL1dot, phiHL2, phiHL2dot, t);
    
end

