function [xFRf, xHRf, xFLf, xHLf, yFRf, yHRf, yFLf, yHLf, ...
    xFRfdot, yFRfdot, xHRfdot, yHRfdot,...
    xFLfdot, yFLfdot, xHLfdot, yHLfdot] = ...
    state_to_feet_coords(...
    xb, xbdot, yb, ybdot, thb, thbdot, ...
    thFR1, thFR1dot, thFR2, thFR2dot, thFR3, thFR3dot, ...
    thHR1, thHR1dot, thHR2, thHR2dot, thHR3, thHR3dot, ...
    thFL1, thFL1dot, thFL2, thFL2dot, thFL3, thFL3dot, ...
    thHL1, thHL1dot, thHL2, thHL2dot, thHL3, thHL3dot)

global lF1 lF2 lF3 lH1 lH2 lH3
global db lb

%-------------------------------------------------------------------------%
% From Mathematica we get
%-------------------------------------------------------------------------%
xFRf=xb+db.*cos(thb)+lF1.*sin(thFR1)+lF2.*sin(thFR2)+lF3.*sin( ...
  thFR3);
yFRf=yb+(-1).*lF1.*cos(thFR1)+(-1).*lF2.*cos(thFR2)+(-1).*lF3.* ...
  cos(thFR3)+db.*sin(thb);
xFRfdot=xbdot+lF1.*thFR1dot.*cos(thFR1)+lF2.*thFR2dot.*cos(thFR2)+ ...
  lF3.*thFR3dot.*cos(thFR3)+(-1).*db.*thbdot.*sin(thb);
yFRfdot=ybdot+db.*thbdot.*cos(thb)+lF1.*thFR1dot.*sin(thFR1)+lF2.* ...
  thFR2dot.*sin(thFR2)+lF3.*thFR3dot.*sin(thFR3);

xHRf=xb+(-1).*((-1).*db+lb).*cos(thb)+lH1.*sin(thHR1)+lH2.*sin( ...
  thHR2)+lH3.*sin(thHR3);
yHRf=yb+(-1).*lH1.*cos(thHR1)+(-1).*lH2.*cos(thHR2)+(-1).*lH3.* ...
  cos(thHR3)+(-1).*((-1).*db+lb).*sin(thb);
xHRfdot=xbdot+lH1.*thHR1dot.*cos(thHR1)+lH2.*thHR2dot.*cos(thHR2)+ ...
  lH3.*thHR3dot.*cos(thHR3)+((-1).*db+lb).*thbdot.*sin(thb);
yHRfdot=ybdot+(-1).*((-1).*db+lb).*thbdot.*cos(thb)+lH1.*thHR1dot.* ...
  sin(thHR1)+lH2.*thHR2dot.*sin(thHR2)+lH3.*thHR3dot.*sin( ...
  thHR3);

xFLf=xb+db.*cos(thb)+lF1.*sin(thFL1)+lF2.*sin(thFL2)+lF3.*sin( ...
  thFL3);
yFLf=yb+(-1).*lF1.*cos(thFL1)+(-1).*lF2.*cos(thFL2)+(-1).*lF3.* ...
  cos(thFL3)+db.*sin(thb);
xFLfdot=xbdot+lF1.*thFL1dot.*cos(thFL1)+lF2.*thFL2dot.*cos(thFL2)+ ...
  lF3.*thFL3dot.*cos(thFL3)+(-1).*db.*thbdot.*sin(thb);
yFLfdot=ybdot+db.*thbdot.*cos(thb)+lF1.*thFL1dot.*sin(thFL1)+lF2.* ...
  thFL2dot.*sin(thFL2)+lF3.*thFL3dot.*sin(thFL3);

xHLf=xb+(-1).*((-1).*db+lb).*cos(thb)+lH1.*sin(thHL1)+lH2.*sin( ...
  thHL2)+lH3.*sin(thHL3);
yHLf=yb+(-1).*lH1.*cos(thHL1)+(-1).*lH2.*cos(thHL2)+(-1).*lH3.* ...
  cos(thHL3)+(-1).*((-1).*db+lb).*sin(thb);
xHLfdot=xbdot+lH1.*thHL1dot.*cos(thHL1)+lH2.*thHL2dot.*cos(thHL2)+ ...
  lH3.*thHL3dot.*cos(thHL3)+((-1).*db+lb).*thbdot.*sin(thb);
yHLfdot=ybdot+(-1).*((-1).*db+lb).*thbdot.*cos(thb)+lH1.*thHL1dot.* ...
  sin(thHL1)+lH2.*thHL2dot.*sin(thHL2)+lH3.*thHL3dot.*sin( ...
  thHL3);
